<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net9.0-windows</TargetFramework>
		<OutputType>WinExe</OutputType>
		<StartupObject>PolicyPlus.Program</StartupObject>
		<MyType>WindowsForms</MyType>
		<DefaultItemExcludes>$(DefaultItemExcludes);$(ProjectDir)**\*.vb</DefaultItemExcludes>
		<LangVersion>latest</LangVersion>
		<UseWindowsForms>true</UseWindowsForms>
		<ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
		<OptionExplicit>On</OptionExplicit>
		<OptionCompare>Binary</OptionCompare>
		<OptionStrict>Off</OptionStrict>
		<OptionInfer>On</OptionInfer>
		<ApplicationIcon>PolicyPlusIcon.ico</ApplicationIcon>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x86'">
		<OutputPath>bin\x86\Debug\</OutputPath>
		<DocumentationFile>bin\Debug\PolicyPlus.xml</DocumentationFile>
		<NoWarn>41999,42016,42017,42018,42019,42020,42021,42022,42032,42036,CS1591</NoWarn>
		<WarningsAsErrors>42030,42104,42108,42109</WarningsAsErrors>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x86'">
		<OutputPath>bin\x86\Release\</OutputPath>
		<DocumentationFile>bin\Release\PolicyPlus.xml</DocumentationFile>
		<NoWarn>41999,42016,42017,42018,42019,42020,42021,42022,42032,42036</NoWarn>
		<WarningsAsErrors>42030,42104,42108,42109</WarningsAsErrors>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>
	<ItemGroup>
		<Import Include="Microsoft.VisualBasic" />
		<Import Include="System" />
		<Import Include="System.Collections" />
		<Import Include="System.Collections.Generic" />
		<Import Include="System.Drawing" />
		<Import Include="System.Diagnostics" />
		<Import Include="System.Windows.Forms" />
		<Import Include="System.Linq" />
		<Import Include="System.Threading.Tasks" />
		<PackageReference Include="System.DirectoryServices" Version="9.0.6" />
		<PackageReference Include="System.IO.FileSystem.AccessControl" Version="5.0.0" />
	</ItemGroup>
	<ItemGroup>
		<Content Include="PolicyPlusIcon.ico" />
	</ItemGroup>
</Project>